version: '3.4'

services:
  app: &app
    build:
      context: .
      dockerfile: ./.docker/development/app/Dockerfile
      args:
        RUBY_VERSION: '2.6.3'
        BUNDLER_VERSION: '2.0.2'
        NODE_MAJOR: '11'
        YARN_VERSION: '1.17.3'
    image: ideacrew/hra_calculator_app:dev-0.1.0
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/bundle
      - node_modules_app:/app/node_modules
      - packs:/app/public/packs
    tmpfs:
      - /tmp
    environment:
      - NODE_ENV=development
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379/
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
      - EDITOR=vi
    secrets:
      - master_key
      - credentials
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle && yarn install --check-files && bundle exec puma -C config/puma.rb"
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - redis

  # web: &web
  #   build:
  #     context: .
  #     dockerfile: ./.docker/development/web/Dockerfile
  #   image: ideacrew/hra_calculator_web:dev-0.1.0
  #   volumes:
  #   volumes:
  #     - ./clients/html:/app
  #     - node_modules_web:/app/node_modules
  #   tmpfs:
  #     - /tmp
  #   environment:
  #     - NODE_ENV=development
  #     - WEB_CONCURRENCY=1
  #     - HISTFILE=/app/log/.bash_history
  #     - EDITOR=vi
  #   secrets:
  #     - ssl_cert
  #     - ssl_key
  #   command: bash -c "npm install  && ng serve --host 0.0.0.0 --port 4200"
  #   ports:
  #     - '4200:4200'
  #   depends_on:
  #     - app

  mongo:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017

  redis:
    image: redis:3.2-alpine
    volumes:
      - redis:/data
    ports:
      - 6379

volumes:
  redis:
  bundle:
  node_modules_web:
  node_modules_app:
  rails_cache:
  packs:
  mongodb:
  mongodb_config:

secrets: 
  master_key:
    file: ./config/master.key
  credentials:
    file: ./config/credentials.yml.enc
  ssl_cert:
    file: ../certs/fullchain.pem
  ssl_key:
    file: ../certs/privkey.pem

