version: '3.4'

services:
  app: &app
    build:
      context: .
      dockerfile: ./.docker/production/app/Dockerfile
      args:
        RUBY_VERSION: '2.6.3'
        BUNDLER_VERSION: '2.0.2'
        NODE_MAJOR: '11'
        YARN_VERSION: '1.17.3'
    image: ideacrew/hra_calculator_app:0.1.0
    volumes:
      - rails_cache:/app/tmp/cache
      - bundle:/bundle
      - node_modules_app:/app/node_modules
    tmpfs:
      - /tmp
    environment:
      - NODE_ENV=production
      - RAILS_ENV=${RAILS_ENV:-production}
      - REDIS_URL=redis://redis:6379/
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
      - EDITOR=vi
    secrets:
      - master_key
      - credentials
    command: bash -c "rm -f tmp/pids/server.pid &&
                      mkdir -p tmp/pids/ &&
                      cat /run/secrets/master_key > /app/config/master.key &&
                      cat /run/secrets/credentials > /app/config/credentials.yml.enc &&
                      bundle &&
                      bundle exec puma -C config/puma.rb"
    ports:
      - 3000
    depends_on:
      - mongo
      - redis

  web: &web
    build:
      context: .
      dockerfile: ./.docker/production/web/Dockerfile
      args:
        API_URL: 'localhost'
    image: ideacrew/hra_calculator_web:0.1.0
    volumes:
      - node_modules_web:/app/node_modules
    tmpfs:
      - /tmp
    environment:
      - NODE_ENV=production
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
      - EDITOR=vi
    secrets:
      - ssl_cert
      - ssl_key
    command: sh -c 'cat /run/secrets/ssl_cert > /etc/ssl/ssl_cert.pem &&
                    cat /run/secrets/ssl_key > /etc/ssl/ssl_key.pem &&
                    mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf-bkp &&
                    sleep 10 &&
                    nginx -g "daemon off;"'
    ports:
      - '8080:80'
      - '443:443'
    depends_on:
      - app

  mongo:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017

  redis:
    image: redis:3.2-alpine
    volumes:
      - redis:/data
    ports:
      - 6379

volumes:
  redis:
  bundle:
  node_modules_app:
  node_modules_web:
  rails_cache:
  mongodb:
  mongodb_config:

secrets: 
  master_key:
    file: ./config/master.key
  credentials:
    file: ./config/credentials.yml.enc
  ssl_cert:
    file: ../certs/fullchain.pem
  ssl_key:
    file: ../certs/privkey.pem
