version: '3.4'

services:
  app: &app
    build:
      context: .
      dockerfile: ./.docker/test/app/Dockerfile
    image: ideacrew/vhc_enrollment_event_source:test-0.1.0
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - packs:/app/public/packs
    tmpfs:
      - /tmp
    environment:
      - NODE_ENV=development
      - RAILS_ENV=${RAILS_ENV:-development}
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
      - EDITOR=vi
    stdin_open: true
    tty: true
    command: bash -c "./test_reports/script/docs.sh"
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017

volumes:
  bundle:
  rails_cache:
  packs:
  mongodb:
  mongodb_config:

secrets: 
  master_key:
    file: ./config/master.key
  credentials:
    file: ./config/credentials.yml.enc
  ssl_cert:
    file: ../certs/fullchain.pem
  ssl_key:
    file: ../certs/privkey.pem